const axios = require('axios');

class OmadaAPI {
  constructor(controllerUrl, username, password) {
    this.baseUrl = controllerUrl.replace(/\/$/, ''); // Remove trailing slash
    this.username = username;
    this.password = password;
    this.token = null;
    this.tokenExpiry = null;
  }

  // Authenticate and get token
  async authenticate() {
    try {
      const response = await axios.post(`${this.baseUrl}/api/v2/login`, {
        username: this.username,
        password: this.password
      });

      if (response.data && response.data.result && response.data.result.token) {
        this.token = response.data.result.token;
        // Set token expiry (assuming 24 hours)
        this.tokenExpiry = new Date(Date.now() + 24 * 60 * 60 * 1000);
        return true;
      }

      throw new Error('Authentication failed');
    } catch (error) {
      console.error('Omada API authentication error:', error.response?.data || error.message);
      throw new Error('Failed to authenticate with Omada controller');
    }
  }

  // Ensure authentication
  async ensureAuthenticated() {
    if (!this.token || !this.tokenExpiry || this.tokenExpiry <= new Date()) {
      await this.authenticate();
    }
  }

  // Get authorization headers
  getAuthHeaders() {
    return {
      'Authorization': `Bearer ${this.token}`,
      'Content-Type': 'application/json'
    };
  }

  // Get all sites
  async getSites() {
    try {
      await this.ensureAuthenticated();

      const response = await axios.get(`${this.baseUrl}/api/v2/sites`, {
        headers: this.getAuthHeaders()
      });

      return response.data.result;
    } catch (error) {
      console.error('Omada API - Get sites error:', error.response?.data || error.message);
      throw new Error('Failed to get sites');
    }
  }

  // Get clients connected to a site
  async getClients(siteId) {
    try {
      await this.ensureAuthenticated();

      const response = await axios.get(`${this.baseUrl}/api/v2/sites/${siteId}/clients`, {
        headers: this.getAuthHeaders()
      });

      return response.data.result;
    } catch (error) {
      console.error('Omada API - Get clients error:', error.response?.data || error.message);
      throw new Error('Failed to get clients');
    }
  }

  // Create voucher
  async createVoucher(siteId, voucherData) {
    try {
      await this.ensureAuthenticated();

      const payload = {
        name: voucherData.name || `MYQL-${Date.now()}`,
        note: voucherData.note || 'Generated by MYQL WIFI system',
        voucherType: 'single', // single use voucher
        duration: voucherData.duration || 24, // hours
        durationUnit: 'hour',
        num: 1, // number of vouchers to create
        uploadLimitEnabled: false,
        downloadLimitEnabled: false,
        uploadLimit: 0,
        downloadLimit: 0,
        rateLimitEnabled: false,
        rateLimit: 0
      };

      const response = await axios.post(
        `${this.baseUrl}/api/v2/sites/${siteId}/vouchers`,
        payload,
        { headers: this.getAuthHeaders() }
      );

      if (response.data && response.data.result && response.data.result.length > 0) {
        return response.data.result[0]; // Return the first voucher
      }

      throw new Error('No voucher created');
    } catch (error) {
      console.error('Omada API - Create voucher error:', error.response?.data || error.message);
      throw new Error('Failed to create voucher');
    }
  }

  // Get vouchers
  async getVouchers(siteId) {
    try {
      await this.ensureAuthenticated();

      const response = await axios.get(`${this.baseUrl}/api/v2/sites/${siteId}/vouchers`, {
        headers: this.getAuthHeaders()
      });

      return response.data.result;
    } catch (error) {
      console.error('Omada API - Get vouchers error:', error.response?.data || error.message);
      throw new Error('Failed to get vouchers');
    }
  }

  // Delete voucher
  async deleteVoucher(siteId, voucherId) {
    try {
      await this.ensureAuthenticated();

      await axios.delete(`${this.baseUrl}/api/v2/sites/${siteId}/vouchers/${voucherId}`, {
        headers: this.getAuthHeaders()
      });

      return true;
    } catch (error) {
      console.error('Omada API - Delete voucher error:', error.response?.data || error.message);
      throw new Error('Failed to delete voucher');
    }
  }

  // Get site statistics
  async getSiteStats(siteId) {
    try {
      await this.ensureAuthenticated();

      const response = await axios.get(`${this.baseUrl}/api/v2/sites/${siteId}/stats`, {
        headers: this.getAuthHeaders()
      });

      return response.data.result;
    } catch (error) {
      console.error('Omada API - Get site stats error:', error.response?.data || error.message);
      throw new Error('Failed to get site statistics');
    }
  }

  // Get controller information
  async getControllerInfo() {
    try {
      await this.ensureAuthenticated();

      const response = await axios.get(`${this.baseUrl}/api/v2/controller`, {
        headers: this.getAuthHeaders()
      });

      return response.data.result;
    } catch (error) {
      console.error('Omada API - Get controller info error:', error.response?.data || error.message);
      throw new Error('Failed to get controller information');
    }
  }
}

module.exports = OmadaAPI;